name: test formatting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify=0.69.0+dfsg1-1build1
      - name: Run Uncrustify
        run: |
          uncrustify --version
          find HelloWorld/Source -prune -false -o -name "*.[hc]" -exec uncrustify --check -c tools/uncrustify.cfg {} +