name: test formatting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find Trailing Whitespace
         # You may pin to the exact commit or the version.
         # uses: harupy/find-trailing-whitespace@master
        uses: harupy/find-trailing-whitespace@v1.0
