name: test formatting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify=0.69.0+dfsg1-1build1
      - name: Check For Trailing Whitespace
        run: |
          set +e
          ERROR=0
          find .  \( -name '.git' -o -path "./FreeRTOS/Test/CBMC/patches" -o -path "./FreeRTOS-Plus" -o -path "./FreeRTOS/Source"  -o  -path "./FreeRTOS/Test/CMock/CMock"  -o -path "./FreeRTOS/Demo" \) -prune -false -o -type f -a -name "*" -exec grep  -In -e "[[:blank:]]$" {} +
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            ERROR=1
          fi
          find FreeRTOS/Demo/Common   \( -name "ethernet" \) -prune -o -false -o -type f -a -name "*" -exec grep --color=yes -In -e "[[:blank:]]$" {} +
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            if [ "$ERROR" -eq "1" ]; then
              exit 1
            fi
            exit 0
          fi