name: Build Runner

on: [push, pull_request]

jobs:
  check_whitespaces:
    runs-on: ubuntu-latest
    name: Check for trailing whitespaces
    steps:
      - uses: actions/checkout@v2
      - name: Find Trailing Whitespace
        uses: harupy/find-trailing-whitespace@v1.0

  start_build:
    runs-on: windows-latest
    name: Build Application
    defaults:
      run:
        shell: cmd
    steps:
    - name: Add NASM and DevEnv to PATH
      uses: nschuetz1311/VisualUefiCompositeAction@main
    - name: Get VisualUefi
      uses: actions/checkout@v3
      with:
       repository: nschuetz1311/VisualUefi
       submodules: 'recursive'

    # There should be a way to split this process.
    # Maybe by including the Lib-artifatcs, to increase build speed.
    - name: Build Libs
      run: |
        cd EDK-II
        devenv EDK-II.sln /build
    - name: Build App
      run: |
        cd Applications\\${{ github.event.repository.name }}
        devenv ${{ github.event.repository.name }}.sln /build

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: EfiOutput
        # path to the output file
        # should use the repo name variable instead of hardcoded name
        path: Applications\\${{ github.event.repository.name }}\\x64\\Release
        if-no-files-found: error
        retention-days: 5

  Create_Release:
    if: |
        "contains(github.event.head_commit.message, '[release]')"

    runs-on: windows-latest
    name: Create Release
    needs: 'start_build'
    defaults:
      run:
       shell: cmd
    steps:
      - run: echo Test
      - name: checkout artifacts
        uses: actions/download-artifact@v3
        with:
         name: EfiOutput
